export const PHASE_NAMES: Record<number, string> = {
  0: "What is Node.js Really?",
  1: "JavaScript for the Node Runtime",
  2: "Node.js Core Architecture",
  3: "File System & OS Interaction",
  4: "Buffers, Binary Data & Encoding",
  5: "Streams & Backpressure",
  6: "Networking Fundamentals",
  7: "HTTP from First Principles",
  8: "Building Web Servers & APIs",
  9: "PostgreSQL Integration",
  10: "Cryptography & Security",
  11: "Child Processes & Worker Threads",
  12: "Observability & Reliability",
  13: "Performance & Scaling",
  14: "Background Jobs & Async Systems",
  15: "Frameworks (After Fundamentals)",
  16: "Advanced Architectures",
};
